[
{"title": "How to change data storage location in InfluxDB?", "date_created": "2021-12-17T16:47:51", "views": "3", "tags": ["influxdb"], "votes": "0", "content": "\r\n                \r\n I am using influxdb as a beginner. I have been working on changing the location of the data storage from its default setting. The examples that I see online are old and do not address the problem in the current situation. In the past, the examples show that we get a .conf file when we downloaded influxdb, but now we do not get any such file (or if we do, then I do not know where this file is located in the system). I have tried many different ways to change the data storage location and one of them is the following: \n influxd --engine-path=\"location\"\n \n However, I would like to run this influxdb instance as a service in windows and I am using NSSM to accomplish my task. In the examples that I have seen online, location of the config file is given as one of the arguments to NSSM, but in the absence of such file, I am not sure how to accomplish the task of running the influxdb instance as a service. Could anyone shed some light on this problem? Is there any way to permanently change the data storage location of the influxdb, so when I create a service using NSSM, it automatically saves data in that new location? Thanks in advance. \n    ", "author_name": "Phantom", "author_questions_number": "0", "author_answers_number": "6", "author_top_tags": ["c++", "scala", "apache-spark", "grafana"], "author_account_date_created": "2015-05-12 05:15:55Z"},
{"title": "CPLEX OPL ERROR RUNTIME : not to type lloType ,", "date_created": "2021-12-17T16:48:01", "views": "7", "tags": ["r", "arrays", "algorithm", "cplex"], "votes": "0", "content": "\r\n                \r\n It is confusing; I do not what the problem is. Does anyone know what the problem is?I get this error,\"opl not to type runtime error\", for some expression in my objective function when I am running the code in CPLEX.i'm working on a thesis with a scheduling problem design so that it's suitable for A2 is deadhead trip, I'm getting an error that i can't output the result with string, please help me review the code, I'll be very grateful My code is as follow: \n `int numLocomotive=...;\nrange RangeLocomotive=1..numLocomotive;\n{string} Pij=...;\n{string} Node=...;\n{string} Locomotive=...;{string} Vd=...;\n{string} Va=...;\n{string} Vs=...;\n{string} Vf=...;\n{string} Exp= Va union Vs;\n{string} Exp= Va union Vs;\n{string} Exp= Va union Vs;\n{string} V= Vd union Va union Vs;\nint ckm=...;\nint cloc=...;\ntuple A{\nstring I;\nstring j;\n}\n  {A} A2 ={ | ordered i,j in Node};\n  int dis=...;\n  dvar boolean x[ in A2];\n  dvar boolean s[Locomotive];\n dvar boolean q[Node][Locomotive];\n\n\n  execute PRE_SETUP\n {\n  cplex.epgap = 0.001;\n  cplex.tilim = 21600;\n  }\n\n  dexpr float Totalcost = sum( in A2)(dis*x[])*ckm + sum(k in Locomotive)s[k]*cloc;\n  minimize Totalcost;\n\n  subject to{\n ct01:\nforall(j in Vd)\n sum( in A2) x[] == 1;\n\nct02:\n forall(i in Exp)\n  sum( in A2) x[] == 1;\n\n ct03:\n forall(j in Vf)\n   sum( in A2) x[] == numLocomotive;   \n\n ct04:\n forall( in A2, k in Locomotive)\n\n   s[k] + x[] == 1;\n\n ct05:\n forall(i in Node, k in Locomotive)\n  q[i][k] == 1;\n\n  ct06:\n forall(i in V)\n sum(k in Locomotive, i in Node) q[i][k] == 1;\n\nct07:\nforall(i in Node, j in Node, k in Locomotive: k in Pij)\n   q[i][k] == q[j][k];\n  forall(i in Node, j in Node, k in Locomotive: k not in Pij)  \n   q[i][k] + q[j][k] == 0;  \n\n  ct08:\n    forall( in A2, k in Locomotive)\n   q[j][k] >= q[i][k] - (1-x[]);\n}      ` \n \n Data \n    ", "author_name": "Jack-5M", "author_questions_number": "0", "author_answers_number": "5", "author_top_tags": ["cplex", "forall", "schedule", "fixed", "model", "scheduled-tasks"], "author_account_date_created": "2021-08-19 10:33:29Z"},
{"title": "required_if validation rule with the array validation rule is not working | Laravel | Validation", "date_created": "2021-12-17T16:39:37", "views": "8", "tags": ["laravel", "laravel-validation"], "votes": "0", "content": "\r\n                \r\n I have the following validation rule in which I need to sure that the  streaming_platforms  array includes the correct information. So the  stream_key  and  stream_url  are required if the  enable  key is true. The  stream_key  should be a string and  stream_url  should be a URL. \n $validator = Validator::make($input, [\n    'name' => 'required|string|min:3|max:255',\n    'type' => 'required|in:private,public',\n    'streaming_platforms.*.stream_url' => 'required_if:streaming_platforms.*.enable,true|url',\n    'streaming_platforms.*.stream_key' => 'required_if:streaming_platforms.*.enable,true|string',\n], [\n    'streaming_platforms.*.stream_url.required_if' => 'The stream url field is required when platform is enable.',\n    'streaming_platforms.*.stream_key.required_if' => 'The stream key field is required when platform is enable.',\n]);\n\nif ($validator->fails()) {\n    return $this->failResponse([\n        \"message\" => $validator->errors()->first(),\n        \"messages\" => $validator->errors(),\n    ], 422);\n}\n \n Everything is working fine, but the URL and string validation rule for stream_url and stream_key respective is fire even though the  enable  value is false. So why does not just stop checking the next rules if the  required_if  is not applied? \n So I tried with the following data. \n {\n    \"name\":\"testing\",\n    \"type\":\"public\",\n    \"streaming_platforms\":[\n        {\"id\":16,\"platform\":\"youtube\",\"enable\":true,\"stream_url\":\"https://www.google.com\",\"stream_key\":\"abdefghijk\"},\n        {\"id\":17,\"platform\":\"facebook\",\"enable\":false,\"stream_url\":null,\"stream_key\":null},\n        {\"id\":18,\"platform\":\"custom\",\"enable\":false,\"stream_url\":null,\"stream_key\":null}\n    ]\n}\n \n So it returns \n \n The streaming_platforms.1.stream_url format is invalid. for the\nFacebook row. \n \n I read somewhere that you can do something like the following i.e by using the  sometimes  rule. but I don't how can I do with the array type data. \n $validator = Validator::make($request->all(), [\n    'name' => ['required', 'min:3', 'max:255'],\n    'is_public_template' => 'boolean',\n\n    'logo' => ['required_if:is_public_template,true'],\n]);\n$validator->sometimes('logo', 'required|image|mimes:jpeg,bmp,png,jpg|dimensions:min_width=128,min_height=128', function ($input) {\n    return $input->is_public_template;\n});\n \n    ", "author_name": "Sachin Kumar", "author_questions_number": "126", "author_answers_number": "55", "author_top_tags": ["laravel", "php", "eloquent", "mysql", "laravel-5", "javascript"], "author_account_date_created": "2016-11-19 13:54:01Z"},
{"title": "How to set the default working directory in VS2022 for ASPNet.Core WebApi", "date_created": "2021-12-17T16:39:38", "views": "6", "tags": ["asp.net-core", "visual-studio-2022"], "votes": "1", "content": "\r\n                \r\n In VS2022 I created a brand new ASP Net Core Web App. I am launching it via IISExpress. \n Within  program.cs  I have added these lines \n         public static void Main(string[] args)\n        {\n            var currentDirectory = Directory.GetCurrentDirectory();\n            Console.WriteLine(currentDirectory);\n\n            CreateHostBuilder(args).Build().Run();\n        }\n \n The current working directory is always the project directory, whereas I am expeting the output directory there. I tried to set my working directory in launchsettings.json - without effect. \n In VS2019 this was working as expected. Am I missing a setting somewhere? \n    ", "author_name": "Stephan Hoffmann", "author_questions_number": "0", "author_answers_number": "10", "author_top_tags": ["c#", "azure-ad-b2c", "asp.net-core-2.2", "odata", "asp.net-core-3.0", "ssas-tabular"], "author_account_date_created": "2014-08-12 16:40:47Z"},
{"title": "Line return in D3.js in a mouseover event", "date_created": "2021-12-17T16:31:32", "views": "11", "tags": ["javascript", "d3.js"], "votes": "1", "content": "\r\n                \r\n I am trying to structure my output in D3.js visualization and I am using \\n line returns\nbut it's not read by JS, any ideas on how it can be solved? \n Thank you very much in advance :) \n .on('mousemove', function(d) {\n    tooltip\n      .style('top', d3.event.pageY - 10 + 'px')\n      .style('left', d3.event.pageX + 10 + 'px')\n      .text(`Number of clones in the class: ${d.data.value/2}   \\r\\n \\n \\r\n             Code of the class: ${d.data.code}\n             Lines at which the clone appears:  ${d.data.lines}`);\n    })\n \n    ", "author_name": "Adam Babs", "author_questions_number": "0", "author_answers_number": "1", "author_top_tags": ["c#", "azure-ad-b2c", "asp.net-core-2.2", "odata", "asp.net-core-3.0", "ssas-tabular"], "author_account_date_created": "2021-11-07 15:30:00Z"},
{"title": "Why can I not use a dictionary to change a matrix?", "date_created": "2021-12-17T16:15:30", "views": "24", "tags": ["python", "list", "dictionary", "matrix"], "votes": "-1", "content": "\r\n                \r\n I have a dictionary that I want to use to change a matrix so I don't have to program a bunch of if statements by hand. However, the program is not recognizing it. \n player_board = [[\"\", \"A\", \"B\", \"C\", \"D\", \"E\", \"F\", \"G\", \"H\"],\n                [\"1\", \" \", \" \", \" \", \" \", \" \", \" \", \" \", \" \"],\n                [\"2\", \" \", \" \", \" \", \" \", \" \", \" \", \" \", \" \"],\n                [\"3\", \" \", \" \", \" \", \" \", \" \", \" \", \" \", \" \"],\n                [\"4\", \" \", \" \", \" \", \" \", \" \", \" \", \" \", \" \"],\n                [\"5\", \" \", \" \", \" \", \" \", \" \", \" \", \" \", \" \"],\n                [\"6\", \" \", \" \", \" \", \" \", \" \", \" \", \" \", \" \"],\n                [\"7\", \" \", \" \", \" \", \" \", \" \", \" \", \" \", \" \"],\n                [\"8\", \" \", \" \", \" \", \" \", \" \", \" \", \" \", \" \"]]\nscreen_encrypt = {\n\"A1\": player_board[1][1],\n\"A2\": player_board[2][1],\n\"A3\": player_board[3][1],\n\"A4\": player_board[4][1],\n\"A5\": player_board[5][1],\n\"A6\": player_board[6][1],\n\"A7\": player_board[7][1],\n\"A8\": player_board[8][1],\n\"B1\": player_board[1][2],\n\"B2\": player_board[2][2],\n\"B3\": player_board[3][2],\n\"B4\": player_board[4][2],\n\"B5\": player_board[5][2],\n\"B6\": player_board[6][2],\n\"B7\": player_board[7][2],\n\"B8\": player_board[8][2],\n \n } \n inp = \"A1\"\nscreen_encrypt[inp] = \"X\"\n\nfor row in player_board:\n    print(row)\n \n This is the the output: \n ['', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']\n['1', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['2', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['3', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['4', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['5', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['6', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['7', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['8', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n \n This is the desired output: \n ['', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']\n['1', 'X', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['2', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['3', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['4', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['5', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['6', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['7', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n['8', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']\n \n    ", "author_name": "Mopps", "author_questions_number": "0", "author_answers_number": "6", "author_top_tags": ["python", "list", "if-statement", "permutation", "key", "matrix"], "author_account_date_created": "2021-10-28 19:25:58Z"},
{"title": "Index Error: list index out of range: when i try to run AI Virtual Mouse", "date_created": "2021-12-17T16:03:18", "views": "6", "tags": ["python", "opencv"], "votes": "0", "content": "\r\n                \r\n Main \n import cv2\nimport numpy as np\nimport HandTrackingModule as htm\nimport time\nimport autopy\n\n##########################\nfrom HandTrackingModule import handDetector\n\nwCam, hCam = 640, 480\nframeR = 100  # Frame Reduction\nsmoothening = 7\n#########################\n\npTime = 0\nplocX, plocY = 0, 0\nclocX, clocY = 0, 0\n\ncap = cv2.VideoCapture(1)\ncap.set(3, wCam)\ncap.set(4, hCam)\ndetector: handDetector = htm.handDetector(maxHands=1)\nwScr, hScr = autopy.screen.size()\n# print(wScr, hScr)\n\nwhile True:\n    # 1. Find hand Landmarks\n    success, img = cap.read()\n    img = detector.findHands(img)\n    lmList, bbox = detector.findPosition(img)\n    # 2. Get the tip of the index and middle fingers\n    if len(lmList) != 0:\n        x1, y1 = lmList[8][1:]\n        x2, y2 = lmList[12][1:]\n        # print(x1, y1, x2, y2)\n\n    # 3. Check which fingers are up\n    fingers = detector.fingersUp()\n    # print(fingers)\n    cv2.rectangle(img, (frameR, frameR), (wCam - frameR, hCam - frameR), (255, 0, 255), 2)\n    # 4. Only Index Finger : Moving Mode\n    if fingers[1] == 1 and fingers[2] == 0:\n        # 5. Convert Coordinates\n        x3 = np.interp(x1, (frameR, wCam - frameR), (0, wScr))\n        y3 = np.interp(y1, (frameR, hCam - frameR), (0, hScr))\n        # 6. Smoothen Values\n        clocX = plocX + (x3 - plocX) / smoothening\n        clocY = plocY + (y3 - plocY) / smoothening\n\n        # 7. Move Mouse\n        autopy.mouse.move(wScr - clocX, clocY)\n        cv2.circle(img, (x1, y1), 15, (255, 0, 255), cv2.FILLED)\n        plocX, plocY = clocX, clocY\n\n    # 8. Both Index and middle fingers are up : Clicking Mode\n    if fingers[1] == 1 and fingers[2] == 1:\n        # 9. Find distance between fingers\n        length, img, lineInfo = detector.findDistance(8, 12, img)\n        print(length)\n        # 10. Click mouse if distance short\n        if length < 40:\n            cv2.circle(img, (lineInfo[4], lineInfo[5]), 15, (0, 255, 0), cv2.FILLED)\n            autopy.mouse.click()\n\n            # 11. Frame Rate\n            cTime = time.time()\n            fps = 1 / (cTime - pTime)\n            pTime = cTime\n            cv2.putText(img, str(int(fps)), (28, 58), cv2.FONT_HERSHEY_PLAIN, 3, (255, 8, 8), 3)\n            # 12. Display\n            cv2.imshow(\"Image\", img)\n            cv2.waitKey(1)\n \n In above code,\nthe error is\n File \"C:/Users/uer/PycharmProjects/AIVirtualMouse/AI.py\", line 38, in  fingers = detector.fingersUp() \nWhat is problem in  fingers = detector.fingersUp()  I don't understand. enter image description here \n hand tracking module \n import cv2\nimport mediapipe as mp\nimport time\nimport math\nimport numpy as np\n\n\nclass handDetector():\n    def __init__(self, mode=False, maxHands=2, detectionCon=0.5, trackCon=0.5):\n        self.mode = mode\n        self.maxHands = maxHands\n        self.detectionCon = detectionCon\n        self.trackCon = trackCon\n\n        self.mpHands = mp.solutions.hands\n        self.hands = self.mpHands.Hands(self.mode, self.maxHands,\n                                        self.detectionCon, self.trackCon)\n        self.mpDraw = mp.solutions.drawing_utils\n        self.tipIds = [4, 8, 12, 16, 20]\n\n    def findHands(self, img, draw=True):\n        imgRGB = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)\n        self.results = self.hands.process(imgRGB)\n        # print(results.multi_hand_landmarks)\n\n        if self.results.multi_hand_landmarks:\n            for handLms in self.results.multi_hand_landmarks:\n                if draw:\n                    self.mpDraw.draw_landmarks(img, handLms,\n                                               self.mpHands.HAND_CONNECTIONS)\n\n        return img\n\n    def findPosition(self, img, handNo=0, draw=True):\n        xList = []\n        yList = []\n        bbox = []\n        self.lmList = []\n        if self.results.multi_hand_landmarks:\n            myHand = self.results.multi_hand_landmarks[handNo]\n            for id, lm in enumerate(myHand.landmark):\n                # print(id, lm)\n                h, w, c = img.shape\n                cx, cy = int(lm.x * w), int(lm.y * h)\n                xList.append(cx)\n                yList.append(cy)\n                # print(id, cx, cy)\n                self.lmList.append([id, cx, cy])\n                if draw:\n                    cv2.circle(img, (cx, cy), 5, (255, 0, 255), cv2.FILLED)\n\n            xmin, xmax = min(xList), max(xList)\n            ymin, ymax = min(yList), max(yList)\n            bbox = xmin, ymin, xmax, ymax\n\n            if draw:\n                cv2.rectangle(img, (xmin - 20, ymin - 20), (xmax + 20, ymax + 20),\n                              (0, 255, 0), 2)\n\n        return self.lmList, bbox\n\n    def fingersUp(self):\n        fingers = []\n        # Thumb\n        if self.lmList[self.tipIds[0]][1] > self.lmList[self.tipIds[0] - 1][1]:\n            fingers.append(1)\n        else:\n            fingers.append(0)\n\n        # Fingers\n        for id in range(1, 5):\n\n            if self.lmList[self.tipIds[id]][2] < self.lmList[self.tipIds[id] - 2][2]:\n                fingers.append(1)\n            else:\n                fingers.append(0)\n\n        # totalFingers = fingers.count(1)\n\n        return fingers\n\n    def findDistance(self, p1, p2, img, draw=True, r=15, t=3):\n        x1, y1 = self.lmList[p1][1:]\n        x2, y2 = self.lmList[p2][1:]\n        cx, cy = (x1 + x2) // 2, (y1 + y2) // 2\n\n        if draw:\n            cv2.line(img, (x1, y1), (x2, y2), (255, 0, 255), t)\n            cv2.circle(img, (x1, y1), r, (255, 0, 255), cv2.FILLED)\n            cv2.circle(img, (x2, y2), r, (255, 0, 255), cv2.FILLED)\n            cv2.circle(img, (cx, cy), r, (0, 0, 255), cv2.FILLED)\n        length = math.hypot(x2 - x1, y2 - y1)\n\n        return length, img, [x1, y1, x2, y2, cx, cy]\n\n\ndef main():\n    pTime = 0\n    cTime = 0\n    cap = cv2.VideoCapture(1)\n    detector = handDetector()\n    while True:\n        success, img = cap.read()\n        img = detector.findHands(img)\n        lmList, bbox = detector.findPosition(img)\n        if len(lmList) != 0:\n            print(lmList[4])\n\n        cTime = time.time()\n        fps = 1 / (cTime - pTime)\n        pTime = cTime\n\n        cv2.putText(img, str(int(fps)), (10, 70), cv2.FONT_HERSHEY_PLAIN, 3,\n                    (255, 0, 255), 3)\n\n        cv2.imshow(\"Image\", img)\n        cv2.waitKey(1)\n\n\nif __name__ == \"__main__\":\n    main()\n \n In handtrackingmodule the error is\n  File \"C:\\Users\\uer\\PycharmProjects\\AIVirtualMouse\\HandTrackingModule.py\", line 65, in fingersUp if self.lmList[self.tipIds[0]][1] > self.lmList[self.tipIds[0] - 1][1]: IndexError: list index out of range \n Error message \n \"C:\\Python 3.7\\python.exe\" C:/Users/uer/PycharmProjects/AIVirtualMouse/AI.py\n[ WARN:0] global D:\\a\\opencv-python\\opencv-python\\opencv\\modules\\videoio\\src\\cap_msmf.cpp (438) `anonymous-namespace'::SourceReaderCB::~SourceReaderCB terminating async callback\nINFO: Created TensorFlow Lite XNNPACK delegate for CPU.\nTraceback (most recent call last):\n  File \"C:/Users/uer/PycharmProjects/AIVirtualMouse/AI.py\", line 38, in \n    fingers = detector.fingersUp()\n  File \"C:\\Users\\uer\\PycharmProjects\\AIVirtualMouse\\HandTrackingModule.py\", line 65, in fingersUp\n    if self.lmList[self.tipIds[0]][1] > self.lmList[self.tipIds[0] - 1][1]:\nIndexError: list index out of range\n\n \n \n My code is showing Index Error and I don't know how to solve I am\nstill beginner. \n This is my first question in stack overflow so I\ndont know how to write properly. \n \n    ", "author_name": "sameer sayyed", "author_questions_number": "0", "author_answers_number": "1", "author_top_tags": ["python", "list", "if-statement", "permutation", "key", "matrix"], "author_account_date_created": "2021-09-02 13:30:49Z"},
{"title": "why is my tesselation of the voronoi diagram not always a covering tesselation?", "date_created": "2021-12-17T15:47:16", "views": "13", "tags": ["python", "shapely", "voronoi"], "votes": "0", "content": "\r\n                \r\n I am trying to render the results of a GA approach to a covering problem.  Earlier , I found  this question  extremely helpful in generating boundaries. Some edge cases do exist: \n I seem to need (often/always? I'm not positive) 4 or more points to generate the zoning (seems like 2 should be the minimum, its a minor detail though). I also, every once in a while, fail to cover the surface with my polygons. Here's an example: \n \n with this output \n ...\n>79, new best f(8) = 1532561.736\n>84, new best f(8) = 1532586.256\n>97, new best f(8) = 1532910.361\nScore: 1532910.361458032\npoints: [(7.385603823101929, 3.8405732260590417), (7.385603823101929, 1.0891597118471825), (6.97653903235321, 6.537437011319787), (6.911445327302822, 7.404222303328822)]\n\npolys: [[(10.0, 5.6165848996388315), (10.0, 3.7685057514544313), (3.394616991360788, 2.46486646895311), (0.0, 2.46486646895311), (0.0, 4.0997682439946175), (10.0, 5.6165848996388315)], [(10.0, 2.46486646895311), (10.0, 0.0), (0.0, 0.0), (0.0, 2.46486646895311), (10.0, 2.46486646895311)], [(0.0, 4.0997682439946175), (0.0, 6.4493508286073835), (10.0, 7.200329250259113), (10.0, 5.6165848996388315), (0.0, 4.0997682439946175)], [(0.0, 6.4493508286073835), (0.0, 10.0), (10.0, 10.0), (10.0, 7.200329250259113), (0.0, 6.4493508286073835)]]\n \n The entire square should be covered. How can I correct this issue? \n The code I am using to generate it is: \n from scipy.spatial import Voronoi #, voronoi_plot_2d\nfrom shapely.geometry import Polygon\n\nfrom voronoi_polygons import voronoi_polygons\n\ndef render_score(score):\n  print('Score:', score)\n\ndef render_zones(points):\n  print(\"points:\", points)\n  vor = Voronoi(points)\n  #fig = voronoi_plot_2d(vor)\n\n  boundary = np.array([[0,0], [0,10], [10,10], [10,0]])\n  boundary_polygon = Polygon(boundary)\n  x, y = boundary.T\n  \n  plt.xlim(round(x.min() - 1), round(x.max() + 1))\n  plt.ylim(round(y.min() - 1), round(y.max() + 1))\n  plt.plot(*np.array(points).T, 'b.')\n\n  diameter = np.linalg.norm(boundary.ptp(axis=0))\n  polys = []\n  for p in voronoi_polygons(vor, diameter):\n      polys.append(list(p.intersection(boundary_polygon).exterior.coords))\n      x, y = zip(*p.intersection(boundary_polygon).exterior.coords)\n      plt.plot(x, y, 'r-')\n\n  plt.show()\n\n  print(\"polys:\", polys)\n\ndef render_plan(centers):\n  pass\n\ndef render_results(agent):\n  render_score(agent.evaluate())\n  zone_centers = agent.predict()\n  render_zones(zone_centers)\n  render_plan(zone_centers)\n \n with  voronoi_polygons.py : \n # src https://stackoverflow.com/questions/23901943/voronoi-compute-exact-boundaries-of-every-region#answer-52727406\n\nfrom collections import defaultdict\nfrom shapely.geometry import Polygon\nimport numpy as np\n\n\ndef voronoi_polygons(voronoi, diameter):\n    \"\"\"\n    Generate shapely.geometry.Polygon objects corresponding to the\n    regions of a scipy.spatial.Voronoi object, in the order of the\n    input points. The polygons for the infinite regions are large\n    enough that all points within a distance 'diameter' of a Voronoi\n    vertex are contained in one of the infinite polygons.\n    \"\"\"\n    centroid = voronoi.points.mean(axis=0)\n\n    # Mapping from (input point index, Voronoi point index) to list of\n    # unit vectors in the directions of the infinite ridges starting\n    # at the Voronoi point and neighbouring the input point.\n    ridge_direction = defaultdict(list)\n    for (p, q), rv in zip(voronoi.ridge_points, voronoi.ridge_vertices):\n        u, v = sorted(rv)\n        if u == -1:\n            # Infinite ridge starting at ridge point with index v,\n            # equidistant from input points with indexes p and q.\n            t = voronoi.points[q] - voronoi.points[p] # tangent\n            n = np.array([-t[1], t[0]]) / np.linalg.norm(t) # normal\n            midpoint = voronoi.points[[p, q]].mean(axis=0)\n            direction = np.sign(np.dot(midpoint - centroid, n)) * n\n            ridge_direction[p, v].append(direction)\n            ridge_direction[q, v].append(direction)\n\n    for i, r in enumerate(voronoi.point_region):\n        region = voronoi.regions[r]\n        if -1 not in region:\n            # Finite region.\n            yield Polygon(voronoi.vertices[region])\n            continue\n        # Infinite region.\n        inf = region.index(-1)              # Index of vertex at infinity.\n        j = region[(inf - 1) % len(region)] # Index of previous vertex.\n        k = region[(inf + 1) % len(region)] # Index of next vertex.\n        if j == k:\n            # Region has one Voronoi vertex with two ridges.\n            dir_j, dir_k = ridge_direction[i, j]\n        else:\n            # Region has two Voronoi vertices, each with one ridge.\n            dir_j, = ridge_direction[i, j]\n            dir_k, = ridge_direction[i, k]\n\n        # Length of ridges needed for the extra edge to lie at least\n        # 'diameter' away from all Voronoi vertices.\n        length = 2 * diameter / np.linalg.norm(dir_j + dir_k)\n\n        # Polygon consists of finite part plus an extra edge.\n        finite_part = voronoi.vertices[region[inf + 1:] + region[:inf]]\n        extra_edge = [voronoi.vertices[j] + dir_j * length,\n                      voronoi.vertices[k] + dir_k * length]\n        yield Polygon(np.concatenate((finite_part, extra_edge)))\n \n In fact, this may be a problem with scipy.spatial.Voronoi itself, as the built-in 2d plotter produces a strange looking result (it is missing a solid-or-dotted line):\n \n    ", "author_name": "roberto tom\u00e1s", "author_questions_number": "110", "author_answers_number": "175", "author_top_tags": ["javascript", "android", "css", "html", "jquery", "ios"], "author_account_date_created": "2011-04-30 16:52:15Z"},
{"title": "Defaulted, explicitly noexcept destructor is not noexcept", "date_created": "2021-12-17T15:32:52", "views": "35", "tags": ["c++", "destructor", "noexcept"], "votes": "1", "content": "\r\n                \r\n I am on GCC version 8.1.0, and am using the type trait  std::is_nothrow_default_constructible_v  to check for throwing destructors (the implementation happens to be using  nothrow()  to check for non throwing constructors). \n However, I have stumbled upon an interesting phenomenon that might be a compiler bug. I'm asking here for confirmation; here is the minimal reproducible example: \n \n#include \n\nstruct B {\n    ~B() noexcept(false) {}\n};\n\nstruct A {\n    B b;\n    ~A() noexcept = default;\n};\n\n\nint main()\n{\n    static_assert(std::is_nothrow_default_constructible_v);\n    return 0;\n}\n \n Note that if i do  ~A() noexcept {}  instead of  ~A() noexcept = default; , the code compiles as expected. \n What is happening here? \n    ", "author_name": "super", "author_questions_number": "17", "author_answers_number": "8", "author_top_tags": ["c++", "oop", "design-patterns", "inheritance", "pointers", "dynamic-programming"], "author_account_date_created": "2021-06-10 16:44:05Z"},
{"title": "transform: translate doesn't work as expected with viewport units", "date_created": "2021-12-17T15:15:09", "views": "20", "tags": ["html", "css"], "votes": "0", "content": "\r\n                \r\n I'm trying to create animation where at the start brand logo is at the middle of the screen and at the end it moves to it's position in navbar. I decided to  transform: translate  with viewport units. But it doesn't stay in center. On wider screen it sticks to right side and on smaller screen it's a little bit off center. Also  position: absolute  isn't an option since I can't bring logo back to navbar. \n Is it possible to center my logo in the middle with only using  transform: translate ? \n \r\n \r\n nav {\n  max-width: 400px;\n  display: flex;\n  justify-content: space-between;\n  margin: auto;\n  background: #aaa;\n  padding: 5px 10px;\n}\n\n.brand {\n  transform: translate(calc(50vw - 50%), calc(50vh - 50%));\n}\n\n.test {\n  position: absolute;\n  top: 50vh;\n  left: 50vw;\n  transform: translate(-50%, -50%);\n} \r\n \n  Brand\n  \n    Home\n    Profile\n  \n\nTEST \r\n \r\n \r\n\n    ", "author_name": "bordax", "author_questions_number": "0", "author_answers_number": "8", "author_top_tags": ["python", "javascript", "reactjs", "html", "flask", "amazon-web-services"], "author_account_date_created": "2016-05-15 14:15:34Z"},
{"title": "Bouncy Castle PGP Decryption Text file Issue", "date_created": "2021-12-17T14:57:38", "views": "8", "tags": ["java", "encryption", "bouncycastle", "pgp"], "votes": "0", "content": "\r\n                \r\n I am using bouncy castle libraries for decrypting PGP encrypted files.\nDecryption is successful but in text files any special characters (including 5 accented capital letters) are replaced with a default character = \u00c3.\nDo you know what causes this problem? how can it be solved? \n    ", "author_name": "Melk", "author_questions_number": "0", "author_answers_number": "4", "author_top_tags": ["certificate", "connection", "security", "csr", "hsm", "openssl"], "author_account_date_created": "2020-10-24 16:05:12Z"},
{"title": "Cannot call 'strategy.close' with argument 'when'='long'", "date_created": "2021-12-17T14:41:02", "views": "9", "tags": ["pine-script"], "votes": "0", "content": "\r\n                \r\n Let me start off by saying I'm very new to  Pine Script  and i think my problem is trivial but i didn't find much on it. \n Let's say for example I want the make a strategy that would buy when  EMA25  crosses over  EMA200  and sell when it goes under without the need for  limit   stop  or  loss \n //@version=5\nstrategy(\"Pine Script EMA Strategy\", overlay = true, initial_capital = 100, default_qty_value = 100, default_qty_type = strategy.percent_of_equity)\n\nEMA25 = ta.ema(close, 25)\nEMA200 = ta.ema(close, 200)\n\nplot(EMA25, color=color.red, title=\"EMA25\")\nplot(EMA200, color=color.yellow, title=\"EMA200\")\n\nbool longPositionCondition = ta.crossover(EMA25, EMA200)\nbool exitLong = ta.crossover(EMA200, EMA25)\n\nif (exitLong)\n    bool exitWorkAround = true\nelse\n    bool exitWorkAround = false\n\nif (longPositionCondition)\n    strategy.entry(\"long\", strategy.long)\n    strategy.close(\"exit\", \"long\", when = exitLong)\n \n Whenever I try to execute this code I get this error: \n Add to Chart operation failed, reason: line 20: Cannot call 'strategy.close' with argument 'when'='long'. An argument of 'literal string' type was used but a 'series bool' is expected \n I've been looking into this problem for a while but I still don't know what exactly what I'm doing wrong, \nit seems to ask for a  boolean  variable in  when =  but says it's  'when'='long'  which as far as I understood is the id for  strategy.entry  so it doesn't make any sense to me. \n    ", "author_name": "omar", "author_questions_number": "1", "author_answers_number": "13", "author_top_tags": ["discord.py", "python", "discord", "visual-studio-2019", "visual-studio", "kotlin"], "author_account_date_created": "2021-01-05 18:04:47Z"},
{"title": "Can I use Firebase Phone Auth without publishing my app in playstore?", "date_created": "2021-12-17T14:26:46", "views": "8", "tags": ["android", "firebase", "react-native", "firebase-authentication"], "votes": "0", "content": "\r\n                \r\n My app is not published in playstore. I tried to use  Firebase Phone Auth  it works fine when I use with test number where the number has fixed otp set from firebase console. But when try to use different number that is not set for testing I get this error. \n  WARN  0 [Error: [auth/app-not-authorized] This app is not authorized to use Firebase Authentication. \nPlease verify that the correct package name and SHA-1 are configured in the Firebase Console. \n[ A safety_net_token was passed, but no matching SHA-256 was registered in the Firebase console. \nPlease make sure that this application\u2019s packageName/SHA256 pair is registered in the Firebase Console. ]]\n \n Build type : Debug\n\"@react-native-firebase/app\": \"^13.1.0\",\n\"@react-native-firebase/auth\": \"^13.1.0\",\n \n    ", "author_name": "Shahrear Bin Amin", "author_questions_number": "9", "author_answers_number": "80", "author_top_tags": ["python", "node.js", "android", "firebase", "firebase-realtime-database", "javascript"], "author_account_date_created": "2019-05-31 19:35:21Z"},
{"title": "What is the data type by which R indexes arrays?", "date_created": "2021-12-17T14:09:21", "views": "22", "tags": ["r"], "votes": "2", "content": "\r\n                \r\n Suppose I have some array,  but the dimension is a priori unknown (not necessarily 3, as in the example below) . \n A=array(1:24, dim=c(2,3,4))\n \n I also have an input vector with length equal to the dimension of this array \n pos=c(2,1,3)\n \n Based on this input vector, I want to return \n A[1:2,1:1,1:3]\n \n How can I do this automatically? In other words, what kind of data  X  do I have to pass to  A[]  so that R understands what I want. \n For example, having  X  be a list does not work: \n A[lapply(pos,function(x) 1:x)]\n \n    ", "author_name": "axelniemeyer", "author_questions_number": "1", "author_answers_number": "3", "author_top_tags": ["r"], "author_account_date_created": "2020-04-22 13:56:40Z"},
{"title": "Strapi Image Upload", "date_created": "2021-12-17T13:50:40", "views": "7", "tags": ["next.js", "strapi"], "votes": "0", "content": "\r\n                \r\n I have an issue with the /upload route in my application. \n I can get it working and uploading, my issue is that /upload route is open and any authenticated can use it, therefore can upload at will and also will be able to post to entires that do they have control over.  Can I set up for example an isAuthenticatedUser policy for the route which checks it the correct authenticated user? \n Thanks \n    ", "author_name": "Jordan Houghton", "author_questions_number": "0", "author_answers_number": "1", "author_top_tags": ["r"], "author_account_date_created": "2021-09-21 11:15:00Z"},
{"title": "Rust data moved E0507 but I can't get the references working", "date_created": "2021-12-17T13:32:17", "views": "46", "tags": ["rust", "move"], "votes": "0", "content": "\r\n                \r\n I'm very new to Rust and for an assignment I have to implement a binary tree called \"SortedContainer\". The problem I ran into is that the data moves somehow and I can't seem to get the references working. \n The error code is  E0507 . It occurs in \"match self.root\" in the insert function from the Sortedcontainer implementation. \n Rust suggests &self but this creates a type error: he expected in BTNode::insert(foundNode, age, name) a Box but found a reference. The foundNode is now the error. Trying to derefence it does not work (*foundNode). The reason for this is that \"move occurs because  *foundNode  has type  Box>  which does not implement the  Copy  Trait. \n Here is my code: \n type ChildNode = Option>>; //Define alias (type); prevents recursive type (= self-reference), points to heap (box). Optional (option)\n\npub struct BTNode{\n    left: ChildNode, //Box prevents recursive type/self-reference; points to object on the heap\n    right: ChildNode,\n    age: T,\n    name: U\n}\n\nimpl BTNode{\n    pub fn new(l: ChildNode, r: ChildNode, a: i32, n: String) -> Self{ //ChildNode very important, otherwise no unit. values allowed.\n        BTNode::{\n            left: l, right: r, age: a, name: n\n        }\n    }\n    pub fn insert(mut node: Box>, age: i32, name: String) -> Box>{\n        if age < node.age {\n            match node.left {\n                None => node.left = Some(Box::new(BTNode::new(None, None, age, name))),\n                Some(foundNode) => return BTNode::insert(foundNode, age, name),\n            }\n        } else if age > node.age { //This else keeps the \"name\" from going out of scope\n            match node.right {\n                None => node.right = Some(Box::new(BTNode::new(None, None, age, name))),\n                Some(foundNode) => return BTNode::insert(foundNode, age, name),\n            }\n        }\n        eprintln!(\"Undefined/Unimplemented behaviour: age already present in tree. Failed to insert into tree\");\n        std::process::exit(0x0100); //Error code 0 on linux, 256 on Windows\n    }\n}\n\npub struct SortedContainer{\n    root: ChildNode\n}\n\nimpl SortedContainer  { //Tree\n    pub fn new() -> Self{\n        SortedContainer::{\n            root: None,\n        }\n    }\n    pub fn insert(&mut self, age: i32, name: String) { //self is a keyword; self      cannot be replaced by say \"tree\";\n        match self.root {     //ERROR E0507 HERE. If &self, then error below\n            None => {\n                self.root = Some(Box::new(BTNode::new(None, None, age, name)));\n            },\n            Some(foundNode) => {\n                BTNode::insert(foundNode, age, name); //If &self, then foundNode has error E0308 mismatched types. Expected struct Box, found reference.\n                           //If dereferenced, then error E0507 again.    \n            }\n        }\n    }\n}\n \n EDIT: this might be some relevant information. It is how I try using the SortedContainer and how I'm testing it. \n fn main() {\n    let mut tree: tree::SortedContainer = tree::SortedContainer::new();\n    tree.insert(32, \"Papa Johns\".to_string()); //This works due to the self parameter in the function \n    tree.insert(24, \"Johan\".to_string());\n    tree.insert(8, \"EvaBeva\".to_string());\n    tree.insert(64, \"PizzaLoverYesYes\".to_string());\n    tree.print();\n}\n \n    ", "author_name": "Idea Flux", "author_questions_number": "0", "author_answers_number": "1", "author_top_tags": ["r"], "author_account_date_created": "2021-09-22 16:28:00Z"},
{"title": "https requests from a Jenkins Job blocked", "date_created": "2021-12-17T13:17:51", "views": "10", "tags": ["api", "jenkins", "https"], "votes": "0", "content": "\r\n                \r\n I'm experiencing an issue with  https requests  sent from a  Jenkins job , which are blocked and do not reach the final server. \n The scenario is as follows: \n \n I have a server where I'm running some  backend , exposing APIs both over  http  and  https  (it's a django + django rest framework backend) \n I implemented a  Rhinoceros Plugin in C# , which needs to perform some rest API requests to the above mentioned server \n On another server, I'm running a  Jenkins job  that is responsible for compiling the plugin, installing it on Rhinoceros and run some operations on Rhinoceros for test purposes \n \n All calls over  http   do work  like a charm from the plugin running on the Jenkins job, but all  https   do not work . \n NOTES : \n \n When manually running the plugin outside Jenkins, the  https  remote request succeed without any issue \n Moreover,  https  requests sent from any other location do work \n When the plugin runs from the Jenkins job no trace of any incoming connection is logged into the backend server, so that makes me believe the request never leaves the Jenkins server \n \n WHAT I TRIED : \n \n I installed the domain certificate locally on the Jenkins server, using  keytool , on the  JAVA_HOME/lib/security/cacerts  keystore \n I tried to install some Jenkins Plugins to skip certificate check or to trust certain domains \n I checked the firewall on the Jenkins machine (adding allow rules for both Java and Rhinoceros applications) \n \n So far, nothing worked.\nAny idea?\nThanks \n    ", "author_name": "lWhitmore", "author_questions_number": "2", "author_answers_number": "4", "author_top_tags": ["apk-expansion-files", "android", "plugins", "cordova", "restkit-0.26.x", "dynamic"], "author_account_date_created": "2013-10-10 13:33:44Z"},
{"title": "wsimport & SOAP service authorization error even though URL does not require proxy/VPN", "date_created": "2021-12-17T13:00:01", "views": "15", "tags": ["java", "maven", "soap", "wsimport"], "votes": "2", "content": "\r\n                \r\n I want to use a SOAP webservice from my application and to generate the neccessary java file using   wsimport. here is my pom.xml: \n \n    jakarta.xml.ws\n    jakarta.xml.ws-api\n    3.0.1\n\n\n    com.sun.xml.ws\n    jaxws-rt\n    3.0.0\n    runtime\n\n\n    com.sun.xml.ws\n    jaxws-ri\n    2.3.2\n    pom\n\n\n...\n\n\n    com.sun.xml.ws\n    jaxws-maven-plugin\n    2.3.2\n    \n    \n        https://signatur.ak-ooe.at/primesign/services/workflowMTOM?wsdl\n    \n    true\n    digitales_signieren.primesign\n    src/main/java\n    \n\n \n As you can see, I want to read the WSDL from  https://signatur.ak-ooe.at/primesign/services/workflowMTOM?wsdl  . I can access this without any proxy or VPN , but when I try to run \n \n mvn clean jaxws:wsimport \n \n I get the error: \n \n [ERROR] Server returned HTTP response code: 401 for URL:\n https://signatur.ak-ooe.at/primesign/services/workflowMTOM?wsdl ,\n\"https://signatur.ak-ooe.at/primesign/services/workflowMTOM?w sdl\"\nneeds authorization, please provide authorization file with read\naccess at C:\\Users\\username.metro\\auth or use -Xauthfile to\ngive the authorization file and on each lin e provide authorization\ninformation using this format :\nhttp[s]://user:password@host:port// \n \n Why would authorization be required here? The URL seems to be publicly accessable \n    ", "author_name": "Christian O.", "author_questions_number": "2", "author_answers_number": "27", "author_top_tags": ["python", "jsf", "primefaces", "pandas", "html", "css"], "author_account_date_created": "2016-03-29 14:08:35Z"},
{"title": "Fractals in L-system", "date_created": "2021-12-17T12:45:41", "views": "15", "tags": ["python", "fractals"], "votes": "0", "content": "\r\n                \r\n def L(pos):\n    #left turn\n    global theta, d\n    x1=pos[0]\n    y1=pos[1]\n    theta += plt.radians(60)\n    return (x1+d*plt.cos(theta),\n            y1+d*plt.sin(theta))\n\ndef R(pos):\n    #right turn\n    global theta, d\n    x1=pos[0]\n    y1=pos[1]\n    theta -= plt.radians(120)\n    return (x1+d*plt.cos(theta),\n            y1+d*plt.sin(theta))\n\ndef F(pos):\n    #forward\n    global theta, d\n    x1=pos[0]\n    y1=pos[1]\n    theta -= plt.radians(300)\n    return (x1+d*plt.cos(theta),\n            y1+d*plt.sin(theta))\n\n#Create L-pattern\n#Start pattern FLRL\n#transformation pattern LRL\nt1 = [R,R,R]\n\n#transformations = [L,R,L]\n#theta =  \n#d=1\n\n#F LRL L LRLR LRL L LRL \nt2 = []\niterations = 8\nfor i in range(iterations):\n    d = d/3\n    for elem in t1:\n        t2.append(elem)\n        for tr in transformations:\n            t2.append(tr)\n    t1=t2\n    t2=[]\n    \n#plotting L-pattern\npos = (0,0)\nx=[0]\ny=[0]\nfor tr in t1:\n    pos=tr(pos)\n    x.append(pos[0])\n    y.append(pos[1])\n\nplt.plot(x,y)\nplt.axis(\"scaled\")\nplt.show()\n\n \n I would like to get the theta(angle) as an input and the variable d which is the length for each function created. My first idea was to have one def() that takes all the arguments instead of separating it into three functions, def L, F and R. This in order to not have settled variables as the angle to create each fractal. \n    ", "author_name": "Lars Andersson", "author_questions_number": "0", "author_answers_number": "2", "author_top_tags": ["canvas", "tkinter", "python"], "author_account_date_created": "2020-05-15 19:30:58Z"},
{"title": "How to transpose 4 rows in a data frame including two columns and show them as column using pandas", "date_created": "2021-12-17T12:28:16", "views": "19", "tags": ["python", "python-3.x", "pandas"], "votes": "2", "content": "\r\n                \r\n date    time    value\n0   01-01-2000  00:00   1\n1   01-01-2000  00:00   2\n2   01-01-2000  00:00   3\n3   01-01-2000  00:00   4\n4   01-01-2000  01:00   5\n5   01-01-2000  01:00   6\n6   01-01-2000  01:00   7\n7   01-01-2000  01:00   8\n \n i have above dataframe i wants to result out to below format \n date    time    value   col1  col2  col3  col4\n0   01-01-2000  00:00   1      2     3     4\n1   01-01-2000  01:00   5      6     7     8\n\n\n \n data list \n date = ['01-01-2000','01-01-2000','01-01-2000','01-01-2000','01-01-2000','01-01-2000','01-01-2000','01-01-2000']\ntime = ['00:00','00:00','00:00','00:00','01:00','01:00','01:00','01:00']\nvalue = [1,2,3,4,5,6,7,8]\n \n    ", "author_name": "Ganesh M", "author_questions_number": "2", "author_answers_number": "12", "author_top_tags": ["python-3.x", "python", "pandas", "random", "list"], "author_account_date_created": "2017-12-26 17:03:22Z"},
{"title": "Does macOS Monterey come with Python3 preinstalled?", "date_created": "2021-12-17T12:12:30", "views": "26", "tags": ["python", "macos"], "votes": "-3", "content": "\r\n                \r\n I just got the 14\" MacBook Pro 2021, running M1 Pro (macOS Monterey 12.1), and I noticed there are two Python installations in the machine, 2.7.18 and 3.8.9, both installed under  /usr/bin . \n cileong@Mac bin % which python\n/usr/bin/python\ncileong@Mac bin % which python3\n/usr/bin/python3\ncileong@Mac bin % python -V\nPython 2.7.18\ncileong@Mac bin % python3 -V\nPython 3.8.9\n \n 2.7.18 is the version that came preinstalled, but is that the case with 3.8.9?  Here  it says py3 came preinstalled, but I cannot find any info about this anywhere else. \n Is it safe to remove it? If yes, what is the best way to remove it cleanly? I plan to install and manage Python with a package manager like Homebrew. \n I am new to the ecosystem so I'm not very familiar with how macOS works yet. \n Any help is welcomed, thank you! \n    ", "author_name": "Bill Ong", "author_questions_number": "0", "author_answers_number": "3", "author_top_tags": ["python", "recursion", "try-except", "nested-lists", "statistics", "pandas"], "author_account_date_created": "2018-08-06 03:45:31Z"},
{"title": "Codeigniter: Don't Allow multiple users to register with same email", "date_created": "2021-12-17T11:56:39", "views": "7", "tags": ["php", "mysql", "database", "duplicates", "codeigniter-3"], "votes": "0", "content": "\r\n                \r\n When 2 or more user registering with same email on same time. It is passing server side validation and allowing to insert as there is no data when checked in DB using form validation \n Even, I've tried to put code exactly above insert method \n Don't want to modify database structure like add unique key or etc \n Please help\nThanks in advance \n    ", "author_name": "Parth Ganatra", "author_questions_number": "5", "author_answers_number": "2", "author_top_tags": ["php", "grocery-crud", "codeigniter", "twitter-bootstrap", "codeigniter-3", "ion-auth"], "author_account_date_created": "2016-03-20 12:40:11Z"},
{"title": "When exactly do I need \"indirect\" with writing recursive enums?", "date_created": "2021-12-17T11:36:04", "views": "52", "tags": ["swift", "enums"], "votes": "4", "content": "\r\n                \r\n I'm surprised to find out that this compiles: \n enum Foo {\n    case one([Foo])\n    // or\n    // case one([String: Foo])\n}\n \n I would have expected the compiler to tell me to add  indirect  to the enum cases, as  Foo  contains more  Foo s.  Array s and  Dictionary s are all value types, so there are no indirection here. To me, this is structurally similar to this: \n enum Foo {\n    case one(Bar)\n}\n\n// arrays and dictionaries are just a struct with either something or nothing in it\n// right?\nstruct Bar {\n    let t: T?\n}\n \n ... which does require me to add  indirect  to the enum. \n Then I tried tuples: \n enum Foo {\n    case one((Foo, Foo))\n}\n \n and this is considered a recursive enum too. I thought arrays and tuples have the same memory layout, and that is why you can convert arrays to tuples using  withUnsafeBytes  and then binding the memory... \n What rules does this follow? Are there actually something special about arrays and dictionaries? If so, are there other such \"special\" types that looks like it should require  indirect , but actually doesn't? \n The Swift Guide is not very helpful. It just says: \n \n A recursive enumeration is an enumeration that has another instance of the enumeration as the associated value for one or more of the enumeration cases. You indicate that an enumeration case is recursive by writing indirect before it, which tells the compiler to insert the necessary layer of indirection. \n \n What \"has another instance of the enumeration\" means is rather vague. It is even possible to interpret it to mean that  case one(Bar)  is not recursive - the case only has an instance of  Bar , not  Foo . \n    ", "author_name": "Sweeper", "author_questions_number": "5,236", "author_answers_number": "268", "author_top_tags": ["java", "swift", "c#", "ios", "generics", "arrays"], "author_account_date_created": "2015-07-20 03:49:47Z"},
{"title": "unable to uninstall angular 13.2.0-next.1 and install 13.1.2", "date_created": "2021-12-17T11:21:45", "views": "15", "tags": ["javascript", "angular", "typescript", "web"], "votes": "-1", "content": "\r\n                \r\n Mistakenly installed angular prelease version. Now unable to uninstall the prelease version and install stable version. \n    ", "author_name": "raviguggilam", "author_questions_number": "0", "author_answers_number": "4", "author_top_tags": ["angular", "angular-guards", "canactivatechild", "canactivate", "rxjs"], "author_account_date_created": "2020-07-14 07:42:12Z"},
{"title": "Delete data from api placeholder json Anguler", "date_created": "2021-12-17T11:01:43", "views": "14", "tags": ["javascript", "angularjs"], "votes": "2", "content": "\r\n                \r\n I am trying to delete the clicked td using the anguler but it dosent work, dosent return any thing, just it get the data\nCould any one help and tell me where my mistake, i am new with useing anguler.\nthanks\nhere is component.ts \n import { Component, OnInit } from '@angular/core';\nimport {HttpClient} from '@angular/common/http'\n\n@Component({\n  selector: 'app-home',\n  templateUrl: './home.component.html',\n  styleUrls: ['./home.component.css']\n})\nexport class HomeComponent implements OnInit {\n\n  dataArray;\n  id;\n  constructor( private http:HttpClient) {\n    this.http.get('https://jsonplaceholder.typicode.com/posts').subscribe(\n      data =>{\n        this.dataArray = data\n      }\n    )\n  }\n\n  ngOnInit(): void {\n    this.delete\n  }\n  delete () {\n    this.http.delete('https://jsonplaceholder.typicode.com/posts/${id}')\n            .subscribe(() => this.id = 'Delete successful');\n            console.log(this.dataArray)\n  }\n\n}\n \n here is my table : \n  \n            \n              \n                \n                  Title\n                  Operations\n                \n              \n              \n                \n                  {{item.title}}\n                      \n                \n              \n            \n \n    ", "author_name": "ismail", "author_questions_number": "0", "author_answers_number": "2", "author_top_tags": ["javascript"], "author_account_date_created": "2021-11-26 09:43:01Z"},
{"title": "Group-Specific Custom Loss in Keras", "date_created": "2021-12-17T10:46:05", "views": "22", "tags": ["python", "tensorflow", "keras"], "votes": "0", "content": "\r\n                \r\n I am trying to create a fairness in-processor and thus want to apply two different loss functions for two different groups. For the privileged group, I want to use plain binary cross-entropy, for the unprivileged group I want to use the same plus a penalty for a certain unfair outcome. I finished the adjusted loss function and it works just fine when I apply it to all observations, but I can't seem to find a way to apply it to just one of the two groups. I can not include a binary variable for group affiliation because it is a sensitive attribute and can not be part of the training or testing data. So what I need is a way to input another tensor containing only the binary group affiliation so that the loss function can depend on it without it being part of the actual training data. Unfortunately, I am quite new to this and don't know where in the Keras source code I could adjust it. If one of you experienced or even solved a similar problem I would absolutely appreciate any hints on how this might be implementable. \n This is what the adjusted loss might look like. For better readability I shortened the penalty function: \n _EPSILON = 10e-8\n\n\ndef _to_tensor(x, dtype):\n    x = tf.convert_to_tensor(x)\n    if x.dtype != dtype:\n        x = tf.cast(x, dtype)\n    return x\n\n\ndef binary_crossentropy_1(output, target, from_logits=False):\n    if not from_logits:\n        epsilon = _to_tensor(_EPSILON, output.dtype.base_dtype)\n        output = tf.clip_by_value(output, epsilon, 1 - epsilon)\n        output = tf.math.log(output / (1 - output))\n\n    return tf.nn.sigmoid_cross_entropy_with_logits(labels=target,\n                                                   logits=output)\n   \ndef penalty(y_true, y_pred):\n    a = []\n    for i in range(len(y_true)):\n      if y_pred[i] < 0.5 and y_true[i] == 1.0:\n        a.append(-0.2)\n      else:\n        a.append(0.0)\n    a = tf.convert_to_tensor(a)\n    return a\n\ndef binary_crossentropy_adjusted_2(y_true, y_pred):\n    sum = binary_crossentropy_1(output = y_pred, target = y_true) + penalty(y_true = y_true, y_pred = y_pred)\n    return K.mean(sum, axis=-1)     \n \n This works, but I can not specify that the penalty should only apply to one of two groups without including the grouping in X_train. \n    ", "author_name": "Tim", "author_questions_number": "0", "author_answers_number": "1", "author_top_tags": ["javascript"], "author_account_date_created": "2021-12-17 10:23:50Z"},
{"title": "Amadeus multicity flight-search request with infants", "date_created": "2021-12-17T10:30:57", "views": "8", "tags": ["php-curl", "amadeus"], "votes": "0", "content": "\r\n                \r\n In Amedeus Api call, I'm passing an infant with an Adult but it return the below error. \n I'm not getting the actual mistake that how to pass an infant with an adult. \n {\n    \"errors\": [\n        {\n            \"code\": 32171,\n            \"title\": \"MANDATORY DATA MISSING\",\n            \"detail\": \"Missing associated Adult Id for HELD_INFANT\",\n            \"source\": {\n                \"pointer\": \"/travelers[2]\"\n            },\n            \"status\": 400\n        }\n    ]\n}\n \n    ", "author_name": "hamid afridi", "author_questions_number": "0", "author_answers_number": "1", "author_top_tags": ["javascript"], "author_account_date_created": "2021-11-24 06:07:20Z"},
{"title": "Open WallectConnect compatible wallets directly when link is shared inside Dapp swift 5", "date_created": "2021-12-17T10:14:24", "views": "13", "tags": ["ios", "swift", "wallet", "dapp", "wallet-connect"], "votes": "0", "content": "\r\n                \r\n I am creating Dapp which needs to connect wallets with  WalletConnect \n let connectionUrl = walletConnect.connect()\n    /// https://docs.walletconnect.org/mobile-linking#for-ios\n    /// **NOTE**: Majority of wallets support universal links that you should normally use in production application\n    /// Here deep link provided for integration with server test app only\n    let deepLinkUrl = \"wc://wc?uri=\\(connectionUrl)\"\n\n    DispatchQueue.main.asyncAfter(deadline: .now() + 1) {\n        if let url = URL(string: deepLinkUrl), UIApplication.shared.canOpenURL(url) {\n            UIApplication.shared.open(url, options: [:], completionHandler: nil)\n        } else {\n            self.handshakeController = HandshakeViewController.create(code: connectionUrl)\n            self.present(self.handshakeController, animated: true)\n        }\n    }\n \n \n It connects with wallet when QR code is generated and scan with wallet app but can we check the installed wallets to open directly? \n    ", "author_name": "Dinesh Kumar", "author_questions_number": "3", "author_answers_number": "17", "author_top_tags": ["ios", "swift", "image-uploading", "response", "alamofire", "xcode"], "author_account_date_created": "2016-09-12 11:28:21Z"},
{"title": "How to use one log4j2 configuration file for runtime in IDE and another log4j2 configuration file for packaging/deployment?", "date_created": "2021-12-17T09:58:12", "views": "11", "tags": ["java", "maven", "configuration", "log4j2", "properties-file"], "votes": "1", "content": "\r\n                \r\n Using Eclipse 06-2021, Maven, log4j2. \n I am using log4j2 framework for logging in my application. I created configuration in resources folder in a log4j2.properties file. \n I defined there some loggers and their levels: \n ...\nlogger.filelogconvert.appenderRef = FileLogConvert\nlogger.fileloggeneral.appenderRef = FileLogGeneral\nrootLogger.appenderRef.console.ref = FileLogGeneral\n\nlogger.fileloggeneral.level = warn\nrootLogger.level = warn\n \n However i need to rewrite this file when i want to deploy application, because i need to change levels from  info  to  warn  or change appender/logger references. \n    ", "author_name": "Wortig", "author_questions_number": "23", "author_answers_number": "55", "author_top_tags": ["java", "jpa", "maven", "eclipse", "derby", "configuration"], "author_account_date_created": "2018-10-18 14:20:23Z"},
{"title": "Write ONGOING output of a command to file in linux", "date_created": "2021-12-17T09:40:42", "views": "9", "tags": ["linux", "file", "command", "output"], "votes": "0", "content": "\r\n                \r\n There is loads of examples of how to do it for a command that produces an output and quits, but how to do it for a command that never quits and continuously updates its output?\nIn such case, those suggestions only write down the first second of command run and never update it. \n Specifically, I need to run badblocks on a disk to test it, but I want to still be able to see how far it got if the machine shuts down or reboots within the time it takes (could be weeks). badblocks has an \"-o\" option, but it only outputs encountered errors, not ongoing progress. \n    ", "author_name": "lockheed", "author_questions_number": "0", "author_answers_number": "4", "author_top_tags": ["linux", "virtualization", "networking", "libvirt", "kvm", "find"], "author_account_date_created": "2014-01-08 09:19:03Z"},
{"title": "Links to files in fileserver in Telegram", "date_created": "2021-12-17T09:25:45", "views": "8", "tags": ["windows", "hyperlink", "telegram", "telegram-bot"], "votes": "0", "content": "\r\n                \r\n Is there any way to transform path to file/folder to links that can be opened from Telegram Desktop in windows explorer.\nLike \"file://server/share/\" or \"file://c:/windows/\" or \"\\server\\share\".\nOther words, path to file, that I get from \"Copy path\" function in windows explorer.\nCan't find any info about it and no answer from Telegram Support. \n Same things goes to Telegram Bot. Only links \"http(s)://\" format \n    ", "author_name": "AlexShep", "author_questions_number": "0", "author_answers_number": "1", "author_top_tags": ["linux", "virtualization", "networking", "libvirt", "kvm", "find"], "author_account_date_created": "2019-11-21 08:45:19Z"},
{"title": "How to extract properties from json format data?", "date_created": "2021-12-17T09:07:00", "views": "27", "tags": ["node.js"], "votes": "1", "content": "\r\n                \r\n I am trying to learn node.js in doing so I came across a problem.\nHere is the code: \n exports.postLogIn = (req, res, next) => {\n  User.find({ name: req.body.username, emailid: req.body.emailid })\n    .then((result) => {\n      if (result.length) {\n        console.log(\"value of result: \" + result);\n        res.render(\"shop\", { logged: true, name: req.body.username });\n      } else {\n        res.render(\"login\", { notlogged: true });\n      }\n    })\n    .catch((err) => {\n      console.log(err);\n    });\n};\n \n When I do\n console.log(result) \n I get output as: \n {\n  _id: new ObjectId(\"61bab8123a555f52d3f190e3\"),\n  name: 'Patrik',\n  emailid: 'patrik@gmail',\n  __v: 0\n}\n \n I want to extract the value of  _id  but when I  console.log(result._id)  I get result as  undefined \n Please guide me on how to extract the value of _id \n    ", "author_name": "Pawan", "author_questions_number": "0", "author_answers_number": "11", "author_top_tags": ["reactjs", "react-router", "react-router-dom", "css", "node.js", "mongodb"], "author_account_date_created": "2021-11-07 07:54:31Z"},
{"title": "Combine of signed and unsigned bytes", "date_created": "2021-12-17T08:47:30", "views": "54", "tags": ["c"], "votes": "-2", "content": "\r\n                \r\n I need to copy 3 variables into 1 variable using  memcpy . Only the first data is copied into payload memory? I have a combination of signed and unsigned variable \n \n int8_t payload[7] = {0};\nvolatile int8_t data1;  //1 byte signed integer \nvolatile int16_t data2;  //2 byte signed integer \nvolatile uint32_t data3;  //4 byte unsigned integer \n\n\nint main() {\n\n    \n        data1 = 0x7F;\n        data2 = 0x7FFF;\n        data3 = 0xFFFFFFFF;\n            \n        memcpy(payload,  (void*)&data1, 1);\n        memcpy(payload+1, (void*)&data2, 2);\n        memcpy(payload+2, (void*)&data3, 4);\n\n    \n    return 0;\n}\n \n Update!!! \nHere is the modified/fixed version.\nI had to change the   int8_t payload[7]  to  uint8_t payload[7]   to fix the overflow\nand my mistake  memcpy(payload+2, (void*)&data3, 4)  to  memcpy(payload+1+2, (void*)&data3, 4) \n uint8_t payload[7] = {0};\nvolatile int8_t data1;  //1 byte signed integer \nvolatile int16_t data2;  //2 byte signed integer \nvolatile uint32_t data3;  //4 byte unsigned integer \n\n\nint main() {\n\n    \n        data1 = 0x7F;\n        data2 = 0x7FFF;\n        data3 = 0xFFFFFFFF;\n            \n        memcpy(payload,  (void*)&data1, 1);\n        memcpy(payload+1, (void*)&data2, 2);\n        memcpy(payload+3, (void*)&data3, 4);\n\n    \n    return 0;\n}\n \n    ", "author_name": "User6996", "author_questions_number": "4", "author_answers_number": "83", "author_top_tags": ["c#", ".net", "winforms", "php", "javascript", "c++"], "author_account_date_created": "2009-12-04 18:41:22Z"},
{"title": "Import c-modules from embedded Python interpreter (pybind11) in a shared object raises an undefined symbol exception", "date_created": "2021-12-17T08:28:07", "views": "21", "tags": ["python", "c++", "shared-libraries", "pybind11"], "votes": "1", "content": "\r\n                \r\n Update (1) : The same problem can be seen with some compiled stdlib modules. This is not related to numpy (I'm removing the numpy tag and numpy from the title) \n I'm writing a shared object (that is a plugin for a software) that contains an embedded python interpreter. The shared object launches an interpreter and the interpreter imports a python module to be executed. If the imported module includes numpy, I get an undefined symbol error. The actual undefined symbol error changes in function of the python version or numpy version, but it is always a struct of the  PyExc_*  family. \n I've simplified the issue to this mimimum example (it comprises actually two files): \n // main.cc\n#include \"pybind11/embed.h\"\nnamespace py = pybind11;\n\nextern \"C\" {\nint main() {\n  py::scoped_interpreter guard{};\n  auto py_module = py::module::import(\"numpy\");\n  auto version   = py_module.attr(\"__version__\");\n  py::print(version);\n  return 0;\n}\n}\n\n// load.cc\n#include \n\nint main() {\n  void * lib = dlopen(\"./libissue.so\", RTLD_NOW);\n  int(*fnc)(void) = (int(*)(void))dlsym(lib, \"main\");\n  fnc();\n  dlclose(lib);\n  return 0;\n}\n \n that I'm compiling with this CMakeFile: \n cmake_minimum_required(VERSION 3.14)\n\ninclude(FetchContent)\nFetchContent_Declare(\n  pybind11\n  GIT_REPOSITORY https://github.com/pybind/pybind11\n  GIT_TAG v2.8.1)\nFetchContent_MakeAvailable(pybind11)\n\nproject(\n  pybind_issue\n  LANGUAGES C CXX\n  VERSION 1.0.0)\n\nadd_library(issue SHARED main.cc)\nset_target_properties(issue PROPERTIES \n  POSITION_INDEPENDENT_CODE ON \n  CXX_STANDARD 11)\ntarget_link_libraries(issue PRIVATE pybind11::embed)\n# also tested with\n# target_link_libraries(main PRIVATE mylib pybind11::lto pybind11::embed pybind11::module)\n\nadd_executable(issue_main main.cc)\nset_target_properties(issue_main PROPERTIES \n  POSITION_INDEPENDENT_CODE ON\n  CXX_STANDARD 11)\ntarget_link_libraries(issue_main PRIVATE pybind11::embed)\n\nadd_executable(loader load.cc)\ntarget_link_libraries(loader PRIVATE ${CMAKE_DL_LIBS})\n \n This CMakeFile compiles three targets: \n \n an executable that loads the interpreter, imports numpy and prints its version \n a shared object that exports a C function that does exactly the same thing \n a simple loader for the shared object, that tries to run the exported function  \"main\"  from the shared object. \n \n If I run the  issue_main  executable, I get the numpy version on screen correctly. If I run  loader  I get this error: \n terminate called after throwing an instance of 'pybind11::error_already_set'\n  what():  ImportError: \n\n\n    https://numpy.org/devdocs/user/troubleshooting-importerror.html\n\n  * The Python version is: Python3.8 from \"/usr/bin/python3\"\n  * The NumPy version is: \"1.20.3\"\n\nand make sure that they are the versions you expect.\nPlease carefully study the documentation linked above for further help.\n\nOriginal error was: /usr/local/lib/python3.8/dist-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyExc_RecursionError\n\n\nAt:\n  /usr/local/lib/python3.8/dist-packages/numpy/core/__init__.py(51): \n  (219): _call_with_frames_removed\n  (848): exec_module\n  (686): _load_unlocked\n  (975): _find_and_load_unlocked\n  (991): _find_and_load\n  (219): _call_with_frames_removed\n  (1050): _handle_fromlist\n  (219): _call_with_frames_removed\n  (961): _find_and_load_unlocked\n\nirb(main):003:1* module TestMain\n=> #\nirb(main):008:0> \nirb(main):009:0> TestMain.main\nterminate called after throwing an instance of 'pybind11::error_already_set'\n  what():  ImportError: \n\nIMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!\n\nImporting the numpy C-extensions failed. This error can happen for\nmany reasons, often due to issues with your setup or how NumPy was\ninstalled.\n\nWe have compiled some common reasons and troubleshooting tips at:\n\n    https://numpy.org/devdocs/user/troubleshooting-importerror.html\n\nPlease note and check the following:\n\n  * The Python version is: Python3.8 from \"/usr/bin/python3\"\n  * The NumPy version is: \"1.20.3\"\n\nand make sure that they are the versions you expect.\nPlease carefully study the documentation linked above for further help.\n\nOriginal error was: /usr/local/lib/python3.8/dist-packages/numpy/core/_multiarray_umath.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyExc_RecursionError\n\n\nAt:\n  /usr/local/lib/python3.8/dist-packages/numpy/core/__init__.py(51): \n  (219): _call_with_frames_removed\n  (848): exec_module\n  (686): _load_unlocked\n  (975): _find_and_load_unlocked\n  (991): _find_and_load\n  (219): _call_with_frames_removed\n  (1050): _handle_fromlist\n  /usr/local/lib/python3.8/dist-packages/numpy/__init__.py(145): \n  (219): _call_with_frames_removed\n  (848): exec_module\n  (686): _load_unlocked\n  (975): _find_and_load_unlocked\n  (991): _find_and_load\n  (219): _call_with_frames_removed\n  (961): _find_and_load_unlocked\n  (991): _find_and_load\n \n The problem is specific on linux (not tested on OSX), while everything goes as expected on Windows (the code changes a bit, reported here for completeness): \n // main.cc\n#include \"pybind11/embed.h\"\nnamespace py = pybind11;\n\nextern \"C\" {\n__declspec(dllexport) int main() {\n  py::scoped_interpreter guard{};\n  auto py_module = py::module::import(\"numpy\");\n  auto version   = py_module.attr(\"__version__\");\n  py::print(version);\n  return 0;\n}\n}\n// load.cc\n#include \n\nint main() {\n  HMODULE lib = LoadLibrary(\"./issue.dll\");\n  int(*fnc)(void) = (int(*)(void))GetProcAddress(lib, \"main\");\n  fnc();\n  FreeLibrary(lib);\n  return 0;\n}\n \n Is there something that I'm missing? \n Notes : \n \n My first though is a bug in pybind cmake, which is why I issued  this bug report \n My problem seems similar to the one described in  this bug report , but I'm not sure, and I'm not sure it is even a bug \n The problem is similar to the  one described here , but I don't think I'm loading the interpreter more than once in the minimal example. I think I have seen a SO question related to the same problem with the same solution (do not load the interpreter more than once), but I cannot find the reference now. \n I've tested with several numpy version (from 1.19 to 1.22, installed from Ubuntu repository, installed from pip, and locally built), but the problem remained. Only the undefined symbol changed (but always a  PyExc_ ) \n Tested with python3.6 and 3.8 in Ubuntu 18.04 and Ubuntu 20.04 \n Tested on pybind 2.6, 2.7, 2.8.1 \n I tired to link to python static library, but it was not compiled with -fPIC thus compilation fails... \n \n Notes on Update (1) : this appears not to be tied to only numpy. If I import  decimal  (a stdlib numeric class with a c-module component) I get the a similar error: \n #include \"pybind11/embed.h\"\nnamespace py = pybind11;\n\nextern \"C\" {\nint main() {\n  py::scoped_interpreter guard{};\n  auto py_module = py::module::import(\"decimal\");\n  auto version   = py_module.attr(\"__name__\");\n  py::print(version);\n  return 0;\n}\n}\n \n Gives me \n terminate called after throwing an instance of 'pybind11::error_already_set'\n  what():  ImportError: /usr/lib/python3.8/lib-dynload/_contextvars.cpython-38-x86_64-linux-gnu.so: undefined symbol: PyContextVar_Type\n\nAt:\n  /usr/lib/python3.8/contextvars.py(1): \n  (219): _call_with_frames_removed\n  (848): exec_module\n  (686): _load_unlocked\n  (975): _find_and_load_unlocked\n  (991): _find_and_load\n  /usr/lib/python3.8/_pydecimal.py(440): \n  (219): _call_with_frames_removed\n  (848): exec_module\n  (686): _load_unlocked\n  (975): _find_and_load_unlocked\n  (991): _find_and_load\n  /usr/lib/python3.8/decimal.py(8): \n  (219): _call_with_frames_removed\n  (848): exec_module\n  (686): _load_unlocked\n  (975): _find_and_load_unlocked\n  (991): _find_and_load\n\n[1]    3095287 abort (core dumped)  ./loader\n \n    ", "author_name": "Matteo Ragni", "author_questions_number": "113", "author_answers_number": "4", "author_top_tags": ["python", "c++", "linux", "c", "ruby", "javascript"], "author_account_date_created": "2013-04-25 10:35:22Z"},
{"title": "How to prevent other user access a page when there is any user still access the page in ReactJS?", "date_created": "2021-12-17T08:06:29", "views": "10", "tags": ["reactjs"], "votes": "0", "content": "\r\n                \r\n Scenario: \n \n I have a list of data to edit \n When I visit the details data page, the data status is \"in review\" and means that other user is restricted to edit this data when I still on the page \n When I do nothing in the details page, the data status reset to previous state and other user can access it \n \n I have tried to solve this problem with updating the data state when the page is didMount, cache the previous data, and revert it back when the page is unmounting. But, I think it is will affect to the database because everytime a user visit the details page, it will send data to the database. \n So, I want to know if there is alternative to solve this problem with a realtime approach in ReactJS. \n    ", "author_name": "Aksal", "author_questions_number": "2", "author_answers_number": "1", "author_top_tags": ["json", "velo", "javascript", "wordpress-theming", "html", "custom-wordpress-pages"], "author_account_date_created": "2021-11-01 10:44:04Z"},
{"title": "Push Notification Jitsi Call in Flutter", "date_created": "2021-12-17T07:42:02", "views": "15", "tags": ["flutter", "push-notification", "jitsi-meet"], "votes": "0", "content": "\r\n                \r\n I am looking for a solution to implement push notification for an incoming Call with jitsi_meet in my flutter app even if the app is in background or closed. Can anyone guide me in the right direction? \n    ", "author_name": "chaempain", "author_questions_number": "0", "author_answers_number": "7", "author_top_tags": ["dart", "flutter", "tree", "recursion", "dictionary", "vlc"], "author_account_date_created": "2019-11-12 08:36:44Z"},
{"title": "\"LNK1104: cannot open file mclmcrrtd.lib\" Error in Qt Creator", "date_created": "2021-12-17T07:20:02", "views": "26", "tags": ["c++", "qt", "qmake", "matlab-compiler"], "votes": "1", "content": "\r\n                \r\n I generated  *.dll  dynamic-link library file by compiling the application I developed in MATLAB using MRC (MATLAB Runtime Compiler). I'm using the MSVC compiler and qmake toolset in the Qt Creator environment to distribute and/or use the procedures in the application I developed in MATLAB in the Windows OS environment. But I'm having trouble adding the dynamic-link libraries (for example  mclmcrrt.lib ,  libmx.lib ,  libmex.lib ,  libmat.lib ,  libfixedpoint.lib , etc.) shared by the MATLAB Runtime Compiler to my project. When I build the project in the Qt Creator environment, I get the following error: \n > LNK1104: cannot open file 'mclmcrrtd.lib'\n\n> U1077: \"\\VS\\Tools\\MSVC\\{Version}\\bin\\HostX86\\x64\\link.EXE\": return code '0x450'\n\n> U1077: \"\\VS\\Tools\\MSVC\\{Version}\\bin\\HostX86\\x64\\nmake.exe\": return code '0x2'\n \n How do I solve this problem? \n    ", "author_name": "Sercan Sebet\u00e7i", "author_questions_number": "54", "author_answers_number": "6", "author_top_tags": ["html", "css", "javascript", "bootstrap-4", "visual-studio-code", "c#"], "author_account_date_created": "2021-01-18 20:35:39Z"},
{"title": "Renaming multiple column in Julia", "date_created": "2021-12-17T06:53:21", "views": "36", "tags": ["dataframe", "julia"], "votes": "2", "content": "\r\n                \r\n I am trying to rename the dataframe columns using the below code- \n function _process_col(df)\n    for col in names(df)\n        print(col)\n        rename!(df, :col => _clean_col_name(col))\n    end\n    return df\nend\n \n But is throws error that col is not present in the dataframe.  rename!(df, :col => _clean_col_name(col))  is treating col as string not as a variable. \n note -  _clean_col_name(col)  is a custom function to process the column name \n Is there any alternative to do this?? \n    ", "author_name": "mlhub", "author_questions_number": "0", "author_answers_number": "7", "author_top_tags": ["machine-learning", "keras", "deep-learning", "multiclass-classification", "python-3.x", "anaconda"], "author_account_date_created": "2020-05-10 09:46:21Z"}
]